### ISSUE TITLE
Exception: KeyError: 'IDENTIFIER'

### ISSUE THREAD

**Issue by szabgab** [ErezTzvi/ML#1]
In this cell:
```
cancer_stat = raw_data.columns['disease state'] # this is what I'm trying to predict
identifier = data['IDENTIFIER']
data = data.drop('IDENTIFIER', axis=1) # irrelevant, need to clean this
```

**Comment by ErezTzvi** [comment]
I think the problem was caused by running the same cell twice.
Anyway, now it's fixed and running the same cell multiple times doesn't cause the KeyError.
Is it working as well on your end?

Thanks!!

**Comment by szabgab** [comment]
I don't know, but it works now.

**Comment by ErezTzvi** [comment]
Great 👯  (:
